#! (C) Copyright 2022- ECMWF.
#! (C) Copyright 2022- Meteo-France.
#!
#! This software is licensed under the terms of the Apache Licence Version 2.0
#! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#! In applying this licence, ECMWF does not waive the privileges and immunities
#! granted to it by virtue of its status as an intergovernmental organisation
#! nor does it submit to any jurisdiction.

MODULE FIELD_${RANK}$${SUFF}$_STACK_MEMBER_MODULE

USE FIELD_BASIC_MODULE
USE FIELD_CONSTANTS_MODULE

#:set fieldTypeList = fieldType.getFieldTypeList (ranks=[RANK], kinds=['JP' + str (SUFF)])

#:for ft in fieldTypeList
USE ${ft.name}$_MODULE
#:endfor
${fieldType.useParkind1 ()}$

IMPLICIT NONE

PRIVATE

#:for ft in fieldTypeList
#:set ftn = ft.name

TYPE, EXTENDS (${ftn}$_WRAPPER) :: ${ftn}$_STACK_MEMBER
  CLASS (FIELD_BASIC), POINTER :: PARENT => NULL ()
CONTAINS
  PROCEDURE :: DELETE_DEVICE_DATA => ${ftn}$_STACK_MEMBER_DELETE_DEVICE_DATA
  PROCEDURE :: CREATE_DEVICE_DATA => ${ftn}$_STACK_MEMBER_CREATE_DEVICE_DATA
END TYPE

PUBLIC :: ${ftn}$_STACK_MEMBER

#:endfor

CONTAINS

#:for ft in fieldTypeList
#:set ftn = ft.name

  SUBROUTINE ${ftn}$_STACK_MEMBER_CREATE_DEVICE_DATA (SELF)
    CLASS(${ftn}$_STACK_MEMBER) :: SELF

    IF (ASSOCIATED (SELF%PARENT)) THEN
      CALL SELF%PARENT%CREATE_DEVICE_DATA ()
    ENDIF

  END SUBROUTINE ${ftn}$_STACK_MEMBER_CREATE_DEVICE_DATA

  SUBROUTINE ${ftn}$_STACK_MEMBER_DELETE_DEVICE_DATA (SELF)
    CLASS(${ftn}$_STACK_MEMBER) :: SELF

    IF (ASSOCIATED (SELF%PARENT)) THEN
      CALL SELF%PARENT%DELETE_DEVICE_DATA ()
    ENDIF

  END SUBROUTINE ${ftn}$_STACK_MEMBER_DELETE_DEVICE_DATA

#:endfor


END MODULE FIELD_${RANK}$${SUFF}$_STACK_MEMBER_MODULE
