name: FieldAPI_Tests

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: pip install fypp

    - name: Install fiat
      run: |
       git clone https://github.com/ecmwf/ecbuild.git
       export PATH=${{github.workspace}}/ecbuild/bin:$PATH
       git clone https://github.com/ecmwf-ifs/fiat.git
       cd fiat
       mkdir build
       cd build
       cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/fiat/install
       make -j
       make install
       cp ${{github.workspace}}/fiat/install/module/parkind_dp/* ${{github.workspace}}/fiat/install/module/fiat/

    - name: Build field api
      run: |
       export fiat_DIR=${{github.workspace}}/fiat/install
       mkdir build
       cd build
       cmake ..
       make -j

    - name: Test
      run: |
       cd build
       export DEV_ALLOC_SIZE=1000000
       ctest
      
